import type { SourceInventory } from './types.ts';

export const SOURCE_INVENTORY: SourceInventory = {
  baseConsonants: [
    'क',
    'ख',
    'ग',
    'घ',
    'ङ',
    'च',
    'छ',
    'ज',
    'झ',
    'ञ',
    'ट',
    'ठ',
    'ड',
    'ढ',
    'ण',
    'त',
    'थ',
    'द',
    'ध',
    'न',
    'ऩ',
    'प',
    'फ',
    'ब',
    'भ',
    'म',
    'य',
    'र',
    'ऱ',
    'ल',
    'ळ',
    'ऴ',
    'व',
    'श',
    'ष',
    'स',
    'ह',
  ],
  extendedConsonants: ['क़', 'ख़', 'ग़', 'ज़', 'ड़', 'ढ़', 'फ़', 'य़', 'ॹ', 'ॺ', 'ॻ', 'ॼ', 'ॾ', 'ॿ', 'ꣻ'],
  independentVowels: [
    'ऄ',
    'अ',
    'आ',
    'इ',
    'ई',
    'उ',
    'ऊ',
    'ऋ',
    'ॠ',
    'ऌ',
    'ॡ',
    'ऍ',
    'ऎ',
    'ए',
    'ऐ',
    'ऑ',
    'ऒ',
    'ओ',
    'औ',
    'ॲ',
    'ॳ',
    'ॴ',
    'ॵ',
    'ॶ',
    'ॷ',
  ],
  dependentVowelSigns: [
    'ा',
    'ि',
    'ी',
    'ु',
    'ू',
    'ृ',
    'ॄ',
    'ॢ',
    'ॣ',
    'ॅ',
    'ॆ',
    'े',
    'ै',
    'ॉ',
    'ॊ',
    'ो',
    'ौ',
    'ऺ',
    'ऻ',
    'ॎ',
    'ॏ',
    'ॕ',
    'ॖ',
    'ॗ',
  ],
  virama: ['्'],
  nukta: ['़'],
  binduSigns: ['ँ', 'ं', 'ः', 'ऀ'],
  vedicSigns: ['॑', '॒', '॓', '॔'],
  vedicRanges: [
    { start: 0xa8e0, end: 0xa8f1, label: 'Devanagari Extended-A Vedic marks' },
    { start: 0x1cd0, end: 0x1cd4, label: 'Vedic tone marks' },
  ],
  combiningMarkRanges: [{ start: 0x0300, end: 0x0361, label: 'Latin combining marks in supplied list' }],
  punctuation: ['।', '॥', '॰', 'ॱ'],
  symbols: ['ऽ', 'ॐ'],
  privateUseSamples: ['\ue001', '\ue002', '\uf156', '\uf176', '\uf186', '\uf187', '\uf188', '\uf196', '', '', ''],
};
